# Generated by Django 6.0.2 on 2026-03-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_perfil_bio_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária em horas')),
                ('descricao', models.TextField()),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('R', 'Rascunho'), ('P', 'Publicado'), ('E', 'Encerrado')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField()),
                ('conteudo', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='homeapp.curso')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('paga', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(limit_choices_to={'is_aluno': True}, on_delete=django.db.models.deletion.CASCADE, to='homeapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_avaliacao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.aula')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_alunos', models.PositiveIntegerField()),
                ('dias_aula', models.CharField(help_text='Ex: Seg, Qua, Sex', max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='homeapp.curso')),
                ('professor', models.ForeignKey(limit_choices_to={'is_professor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeapp.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.turma'),
        ),
    ]
