# Generated by Django 6.0.2 on 2026-03-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_curso_aula_matricula_nota_pagamento_presenca_turma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='max_alunos',
        ),
    ]
