# Generated by Django 6.0.2 on 2026-03-03 16:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_turma_max_alunos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={},
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='conteudo',
            new_name='anotacoes',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='video_url',
        ),
        migrations.AddField(
            model_name='aula',
            name='data',
            field=models.DateField(default=datetime.datetime(2026, 3, 3, 16, 3, 31, 706798, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='homeapp.turma'),
        ),
    ]
