# Generated by Django 6.0.2 on 2026-03-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_aula_options_rename_conteudo_aula_anotacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='curso',
            new_name='turma',
        ),
    ]
