# Generated by Django 6.0.2 on 2026-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_rename_curso_aula_turma'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('T', 'Trancada'), ('C', 'Cancelada')], default='A', max_length=1),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='paga',
        ),
    ]
